server:
  port: 8082

spring:
  application:
    name: catalog-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:daraz_user}:${MONGO_PASSWORD:daraz_pass}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/daraz_catalog?authSource=admin
      database: daraz_catalog
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

kafka:
  topic:
    catalog-events: catalog-events
